version: 5.0.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget restore
build:
  verbosity: normal
before_test:
- ps: '& "$env:APPVEYOR_BUILD_FOLDER\Resources\Scripts\Setup MIDI ports.ps1"'
test:
  assemblies:
    except:
    - '**\*.Benchmarks.dll'
artifacts:
- path: TestResult.xml
  name: Test results
skip_commits:
  files:
    - '**/*.md'
    - '**/*.nuspec'